---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/RedundantSelf:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
Style/RedundantStringEscape:
  Exclude:
  - app/helpers/eac_rails_utils/menus_helper.rb
Style/StringConcatenation:
  Exclude:
  - lib/eac_rails_utils/htmlbeautifier.rb
  - lib/eac_rails_utils/models/fetch_errors.rb
Style/StringLiterals:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
  - lib/activemodel/associations.rb
Style/SuperWithArgsParentheses:
  Exclude:
  - app/helpers/eac_rails_utils/open_graph_protocol_helper.rb
Style/SymbolArray:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
