---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/FrozenStringLiteralComment:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
  - lib/active_record/associations/has_many_for_active_model_association.rb
  - lib/activemodel/associations.rb
Style/GuardClause:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
Style/HashEachMethods:
  Exclude:
  - app/helpers/eac_rails_utils/open_graph_protocol_helper.rb
  - lib/eac_rails_utils/models/fetch_errors.rb
Style/HashTransformValues:
  Exclude:
  - app/helpers/eac_rails_utils/data_table_helper/data_table/value_cell.rb
Style/IfUnlessModifier:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
  - lib/activemodel/associations.rb
Style/MapToHash:
  Exclude:
  - app/helpers/eac_rails_utils/data_table_helper/data_table/value_cell.rb
Style/MutableConstant:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
Style/OpenStructUse:
  Exclude:
  - lib/eac_rails_utils/models/tableless/build_attributes.rb
Style/PercentLiteralDelimiters:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
Style/PerlBackrefs:
  Exclude:
  - lib/eac_rails_utils/models/tableless_associations/override_methods.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - config/initializers/json.rb
  - lib/eac_rails_utils/patches/active_model.rb
  - lib/eac_rails_utils/patches/numeric.rb
  - spec/helpers/eac_rails_utils/common_form_helper_spec.rb
  - spec/helpers/eac_rails_utils/data_table_helper_spec.rb
  - spec/helpers/eac_rails_utils/formatter_helper_spec.rb
  - spec/lib/eac_rails_utils/menus/group_spec.rb
  - spec/lib/eac_rails_utils/models/fetch_errors_spec.rb
  - spec/lib/eac_rails_utils/models/tableless/belongs_to_spec.rb
  - spec/lib/eac_rails_utils/models/tableless/has_many_to_spec.rb
  - spec/lib/eac_rails_utils/models/tableless_spec.rb
  - spec/lib/eac_rails_utils/models/validations_spec.rb
  - spec/lib/eac_rails_utils/patches/numeric/number_helper_spec.rb
  - spec/lib/rubocop_check_spec.rb
  - spec/spec_helper.rb
  - spec/support/rails_app_append/db/migrate/20230529233000_create_immutable_stubs.rb
  - spec/validators/eac_rails_utils/cpf_validator_spec.rb
  - spec/validators/eac_rails_utils/immutable_validator_spec.rb
  - spec/validators/eac_rails_utils/yaml_validator_spec.rb
Style/RedundantLineContinuation:
  Exclude:
  - lib/eac_rails_utils/models/tableless_associations/override_methods.rb
Style/RedundantReturn:
  Exclude:
  - app/helpers/eac_rails_utils/data_table_helper/column.rb
Style/RedundantSelf:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
Style/RedundantStringEscape:
  Exclude:
  - app/helpers/eac_rails_utils/menus_helper.rb
Style/StringConcatenation:
  Exclude:
  - lib/eac_rails_utils/htmlbeautifier.rb
  - lib/eac_rails_utils/models/fetch_errors.rb
Style/StringLiterals:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
  - lib/activemodel/associations.rb
Style/SuperWithArgsParentheses:
  Exclude:
  - app/helpers/eac_rails_utils/open_graph_protocol_helper.rb
Style/SymbolArray:
  Exclude:
  - lib/active_record/associations/builder/has_many_for_active_model.rb
