require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.7
  Exclude:
    - '**/*/db/schema.rb'
    - lib/active_record/**/*
    - lib/activemodel/associations.rb

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - '**/db/migrate/*'
    - 'test/**/*_test.rb'

Rails/ApplicationRecord:
  Enabled: false

Rails/HelperInstanceVariable:
  Exclude:
    - app/helpers/eac_rails_utils/common_form**/**/*.rb
    - app/helpers/eac_rails_utils/data_table**/**/*.rb
    - app/helpers/eac_rails_utils/menus_helper**/**/*.rb
    - app/helpers/eac_rails_utils/open_graph_protocol_helper.rb

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - lib/eac_rails_utils/models/tableless_associations/override_methods.rb

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RedundantBegin:
  Exclude:
    - lib/eac_rails_utils/models/tableless_associations/override_methods.rb

Style/RedundantSelf:
  Exclude:
    - lib/eac_rails_utils/models/tableless_associations/active_record_reflection.rb
    - lib/eac_rails_utils/models/tableless_associations/override_methods.rb

Style/StringLiterals:
  Exclude:
    - lib/eac_rails_utils/models/tableless_associations/active_record_reflection.rb
    - lib/eac_rails_utils/models/tableless_associations/association_scope_extension.rb
    - lib/eac_rails_utils/models/tableless_associations/override_methods.rb
